from app.models import Project, Scan
from app.services.analysis_service import calculate_reality_score


def build_markdown_report(project: Project, scan: Scan) -> str:
    gaps = list(scan.gaps)
    score = calculate_reality_score([_gap_like(gap.severity) for gap in gaps])
    severity_counts = {
        "High": sum(1 for gap in gaps if gap.severity == "High"),
        "Medium": sum(1 for gap in gaps if gap.severity == "Medium"),
        "Low": sum(1 for gap in gaps if gap.severity == "Low"),
    }

    lines = [
        f"# RealityCheck AI Report: {project.repo_owner}/{project.repo_name}",
        "",
        f"- Reality Score: **{score}/100**",
        f"- Total Gaps: **{len(gaps)}**",
        f"- High: **{severity_counts['High']}**",
        f"- Medium: **{severity_counts['Medium']}**",
        f"- Low: **{severity_counts['Low']}**",
        f"- Files Scanned: **{scan.total_files}**",
        "",
        "## Summary",
        "",
        "RealityCheck AI compared documentation claims, frontend API calls, backend routes, environment variables, dependency signals, and deployment configuration.",
        "",
        "## Detected Signals",
        "",
        f"- Frontend detected: {'yes' if scan.frontend_detected else 'no'}",
        f"- Backend detected: {'yes' if scan.backend_detected else 'no'}",
        f"- Docs detected: {'yes' if scan.docs_detected else 'no'}",
        f"- Docker detected: {'yes' if scan.docker_detected else 'no'}",
        f"- docker-compose detected: {'yes' if scan.docker_compose_detected else 'no'}",
        f"- .env example detected: {'yes' if scan.env_detected else 'no'}",
        "",
        "## Gaps",
        "",
    ]

    if not gaps:
        lines.extend(["No gaps were detected.", ""])
    else:
        for index, gap in enumerate(gaps, start=1):
            lines.extend(
                [
                    f"### {index}. [{gap.severity}] {gap.category}",
                    "",
                    f"- Claim: {gap.claim_text}",
                    f"- Reality: {gap.reality_text}",
                    f"- Source: {gap.source_file or 'unknown'}",
                    f"- Affected: {gap.affected_file or 'unknown'}",
                    "",
                    "**Explanation**",
                    "",
                    gap.explanation,
                    "",
                    "**Recommended Fix**",
                    "",
                    gap.suggested_fix,
                    "",
                ]
            )

    lines.extend(
        [
            "## Recommendations",
            "",
            "Prioritize high-severity API, auth, environment, and deployment gaps first because they are most likely to break runtime behavior or production onboarding.",
            "",
            "_Generated by RealityCheck AI._",
            "",
        ]
    )
    return "\n".join(lines)


class _gap_like:
    def __init__(self, severity: str) -> None:
        self.severity = severity
